const {
    PROD,
    VITE_BASEURL,
    VITE_CONNECT_SRC_DEV,
    VITE_CONNECT_SRC_PROD,
    VITE_OFFLINE_MODE,
    VITE_AXIOS_WITH_CREDENTIALS,
    VITE_ENVIRONMENT_NAME,
} = import.meta.env;

export const V_BASE_URL = VITE_BASEURL;
export const V_ENV_MODE = PROD ? 'production' : 'development';
export const V_OFFLINE_MODE = VITE_OFFLINE_MODE;
export const V_AXIOS_WITH_CREDENTIALS = VITE_AXIOS_WITH_CREDENTIALS;
export const V_ENVIRONMENT_NAME = VITE_ENVIRONMENT_NAME;

export const V_CONNECT_CSP_SRC = PROD ? VITE_CONNECT_SRC_PROD : VITE_CONNECT_SRC_DEV;
